### PR TITLE
feat: add integration tests

### PR DESCRIPTION
**Pull request by parabolic**
**Changes**
- Update the README
- fix the tests (need test docker image update)
- bump inspec-gcp version to the latest
- remove bucket tests and add gcloud and gcp tests
- set the versions to allow terraform 0.13
- change kitchen.yml to be more standardized

**Notes**

Although the terraform module works with 0.13 this PR does not solve a present issue with the tests due to outdated inspec version. I was not able to figure out how to update the docker image to get the a more recent inspec version. With the present version it was failing with the following error
```sh
inspec-gcp: Verifying
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #verify action: [Train::Transports::Gcp::Connection does not implement #run_command_via_connection()] on simple-example-loc
al
>>>>>> ----------------------

```
After some debugging I did the following steps to get the tests working.
```sh
make docker_test_prepare
docker run --rm -it -e SERVICE_ACCOUNT_JSON -v "$(pwd)":/workspace gcr.io/cloud-foundation-cicd/cft/developer-tools:0
gem update inspec
gem update kitchen-terraform
gem install --default -v4.22.8 inspec
gem uninstal inspec 3.9.3

/usr/local/bin/test_integration.sh
```
I would kindly ask for your help on how to get a more recent docker build with the latest version of inspec.

**Integration Tests Output**
```sh
Profile: simple_example
Version: (not specified)
Target:  local://

  ✔  gcloud: Gcloud checks: enabled compute api, and cloud router existence
     ✔  Command: `gcloud --project=ci-cloud-router-afab services list --enabled` exit_status is expected to eq 0
     ✔  Command: `gcloud --project=ci-cloud-router-afab services list --enabled` stderr is expected to eq ""
     ✔  Command: `gcloud --project=ci-cloud-router-afab services list --enabled` stdout is expected to match "compute.googleapis.com"
     ✔  JSON from command: gcloud compute routers describe simple-example-cicada --region=europe-west1 --project=ci-cloud-router-afab --format=json name
is expected to eq "simple-example-cicada"
     ✔  JSON from command: gcloud compute routers describe simple-example-cicada --region=europe-west1 --project=ci-cloud-router-afab --format=json kind
is expected to eq "compute#router"
     ✔  JSON from command: gcloud compute routers describe simple-example-cicada --region=europe-west1 --project=ci-cloud-router-afab --format=json regio
n is expected to eq "https://www.googleapis.com/compute/v1/projects/ci-cloud-router-afab/regions/europe-west1"
     ✔  JSON from command: gcloud compute routers describe simple-example-cicada --region=europe-west1 --project=ci-cloud-router-afab --format=json selfL
ink is expected to eq "https://www.googleapis.com/compute/v1/projects/ci-cloud-router-afab/regions/europe-west1/routers/simple-example-cicada"


Profile Summary: 1 successful control, 0 control failures, 0 controls skipped
Test Summary: 7 successful, 0 failures, 0 skipped
$$$$$$ Finished verifying the 'local' system.
$$$$$$ Verifying the 'inspec-gcp' system...

Profile: simple_example
Version: (not specified)
Target:  gcp://ci-account@ci-cloud-router-afab.iam.gserviceaccount.com

  ✔  gcp: GCP Resources
     ✔  Router simple-example-cicada is expected to exist
     ✔  Router simple-example-cicada name is expected to eq "simple-example-cicada"
     ✔  Router simple-example-cicada region is expected to match /\/europe-west1$/
     ✔  Router dupe is expected not to exist


Profile: Google Cloud Platform Resource Pack (inspec-gcp)
Version: 1.7.0
Target:  gcp://ci-account@ci-cloud-router-afab.iam.gserviceaccount.com

     No tests executed.

Profile Summary: 1 successful control, 0 control failures, 0 controls skipped
Test Summary: 4 successful, 0 failures, 0 skipped
$$$$$$ Finished verifying the 'inspec-gcp' system.
$$$$$$ Finished verifying the systems.
       Finished verifying <simple-example-local> (0m10.80s).
-----> Test Kitchen is finished. (0m14.19s)
```

### CODE REVIEW

**Comment by parabolic** [comment]
Hi @bharathkkb thank you for your review.
> pin the tools image to 0.12.0. Example PR

The tag 0.12.0 of the gcr.io/cloud-foundation-cicd/cft/developer-tools images has **terraform 0.12.xxx**, meaning we cannot use it since we are testing against **terraform 0.13**. Tag 0 for cft/developer-tools means the latest image.

> add the kitchen workaround. Example commit

This was already done https://github.com/terraform-google-modules/terraform-google-cloud-router/pull/11/files#diff-fdbca9ed07a634829a3548f874dc925aR18 

>  nit: We tend to hardcode most of these rather than providing a default via variables for ease of readability. So I propose we keep it like before.

This will render the tests unusable, since the terraform test configuration calls the example as a module which in turn calls the main module. In order for the test to work it needs to pass the required variables which in our case are the ones that I've introduced. As an example, we can see the same variables defined in the network module https://github.com/terraform-google-modules/terraform-google-network/blob/master/examples/simple_project/main.tf#L33-L34
Otherwise we get the following errors.
```sh

       Error: Unsupported argument

         on main.tf line 30, in module "example":
         30:   project = var.project_id

       An argument named "project" is not expected here.


       Error: Unsupported argument

         on main.tf line 31, in module "example":
         31:   name    = random_pet.main.id

       An argument named "name" is not expected here.


       Error: Unsupported argument

         on main.tf line 32, in module "example":
         32:   network = module.vpc.network_name

       An argument named "network" is not expected here.


       Error: Unsupported argument

         on main.tf line 33, in module "example":
         33:   region  = var.region

       An argument named "region" is not expected here.

```
Having said that, I've tried using the 0.13 tag of the cft/developer-tools images and even though it has terraform 0.13 included, inspec and kitchen-terraform are outdated and I get the same error as before.
```
inspec-gcp: Verifying
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #verify action: [Train::Transports::Gcp::Connection does not implement #run_command_via_connection()] on simple-example-loc
al
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```
```sh
docker run --rm -it \
>         -e SERVICE_ACCOUNT_JSON \
>         -v $(pwd):/workspace \
>         gcr.io/cloud-foundation-cicd/cft/developer-tools:0.13.0
Loading /usr/local/bin/task_helper_functions.sh from ~/.bashrc
Invoking init_credentials from ~/.bashrc
Disable this behavior by setting CFT_DISABLE_INIT_CREDENTIALS=yes
Activated service account credentials for: [xxx@xxxxxx.gserviceaccount.com]
[root@ffd0f846e0a9 workspace]# inspec -v
3.9.3

Your version of InSpec is out of date! The latest version is 4.22.8.
```

After checking out the bucket that has all the images https://console.cloud.google.com/gcr/images/cloud-foundation-cicd/GLOBAL/cft/developer-tools?gcrImageListsize=30 I see that the latest is 0.13.2 is also tag 0 which I am using in my commit.

Is there any way we can bump the inspec and kitchen terraform on the `cft/developer-tools` image ?
Cheers!

**Comment by bharathkkb** [comment]
Hi @parabolic 
> we cannot use it since we are testing against terraform 0.13.

We wont being testing against 0.13 until later in Q4. Currently the goal is to relax the constraints to allow users who want to try out 0.13. Hence, I recommend we pin image to `0.12.0`.

> This was already done

Thanks, missed that :) 

> In order for the test to work it needs to pass the required variables

I was suggesting we hardcode whatever may not be required dynamically like name/region while keeping project_id etc. Not a blocker, just a nit :) 

> I've taken the liberty of opening an issue on the link you've provided.

Thanks! I will take a look later. Having you tried inspec tests with the `0.12.0` image?

**Comment by parabolic** [comment]
@bharathkkb I ran the tests with 0.12.0 tag and all the terraform resources were created but the tests failed with the same error. Inspec is the same version (3.9.3) as well.
Cheers!

File: examples/simple/variables.tf [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+}
+
+variable "network" {
+  type        = string
+  description = "A reference to the network to which this router belongs"
+}
+
+variable "project" {
+  type        = string
+  description = "The GCP project ID"
```
Comment (chrhansen) [inline examples/simple/variables.tf:13]: The string-version of the integer-version (which I think is also persisted as string) of the ID?

File: test/fixtures/simple_example/variables.tf [hunk 2]
```diff
@@ -18,3 +18,9 @@ variable "project_id" {
   description = "The ID of the project in which to provision resources."
   type        = string
 }
+
+variable "region" {
+  description = "The ID of the project in which to provision resources."
```
Comment (chrhansen) [inline test/fixtures/simple_example/variables.tf:23]: This description doesn't match the variable-name nor the default value.

**Comment by parabolic** [comment]
@bharathkkb this PR with the latest inspec was merged, and now the DOCKER_TAG_VERSION_DEVELOPER_TOOLS should be set to 0.13.3, how do we proceed ?

File: examples/simple/variables.tf (hunk 1 above)
Comment (parabolic) [reply examples/simple/variables.tf:13]: So it is the ID field and not the Name field. 
According to google it has some limitations, namely 
> Project ID can have lowercase letters, digits, or hyphens. It must start with a lowercase letter and end with a letter or number.
>The project ID is the globally unique identifier for your project. You cannot change the project ID after the project is created.

**Comment by parabolic** [comment]
I ran the `0.13.3` tag of the `DOCKER_TAG_VERSION_DEVELOPER_TOOLS` image and I can confirm that it's working
```sh
Profile: simple_example
Version: (not specified)
Target:  local://

  ✔  gcloud: Gcloud checks: enabled compute api, and cloud router existence
     ✔  Command: `gcloud --project=ci-cloud-router-655a services list --enabled` exit_status is expected to eq 0
     ✔  Command: `gcloud --project=ci-cloud-router-655a services list --enabled` stderr is expected to eq ""
     ✔  Command: `gcloud --project=ci-cloud-router-655a services list --enabled` stdout is expected to match "compute.googleapis.com"
     ✔  JSON from command: gcloud compute routers describe simple-example-parrot --region=europe-west1 --project=ci-cloud-router-655a --format=json name
is expected to eq "simple-example-parrot"
     ✔  JSON from command: gcloud compute routers describe simple-example-parrot --region=europe-west1 --project=ci-cloud-router-655a --format=json kind
is expected to eq "compute#router"
     ✔  JSON from command: gcloud compute routers describe simple-example-parrot --region=europe-west1 --project=ci-cloud-router-655a --format=json regio
n is expected to eq "https://www.googleapis.com/compute/v1/projects/ci-cloud-router-655a/regions/europe-west1"
     ✔  JSON from command: gcloud compute routers describe simple-example-parrot --region=europe-west1 --project=ci-cloud-router-655a --format=json selfL
ink is expected to eq "https://www.googleapis.com/compute/v1/projects/ci-cloud-router-655a/regions/europe-west1/routers/simple-example-parrot"


Profile Summary: 1 successful control, 0 control failures, 0 controls skipped
Test Summary: 7 successful, 0 failures, 0 skipped
$$$$$$ Finished verifying the 'local' system.
$$$$$$ Verifying the 'inspec-gcp' system...

Profile: simple_example
Version: (not specified)
Target:  gcp://ci-account@ci-cloud-router-655a.iam.gserviceaccount.com

  ✔  gcp: GCP Resources
     ✔  Router simple-example-parrot is expected to exist
     ✔  Router simple-example-parrot name is expected to eq "simple-example-parrot"
     ✔  Router simple-example-parrot region is expected to match /\/europe-west1$/
     ✔  Router dupe is expected not to exist


Profile: Google Cloud Platform Resource Pack (inspec-gcp)
Version: 1.7.0
Target:  gcp://ci-account@ci-cloud-router-655a.iam.gserviceaccount.com

     No tests executed.

Profile Summary: 1 successful control, 0 control failures, 0 controls skipped
Test Summary: 4 successful, 0 failures, 0 skipped
$$$$$$ Finished verifying the 'inspec-gcp' system.
$$$$$$ Finished verifying the systems.
       Finished verifying <simple-example-local> (0m12.32s).
-----> Test Kitchen is finished. (0m14.22s)
```

**Review by chrhansen — APPROVED** [review]

File: test/setup/main.tf [hunk 3]
```diff
@@ -18,15 +18,15 @@ module "project" {
   source  = "terraform-google-modules/project-factory/google"
   version = "~> 3.0"
```
Comment (bharathkkb) [inline test/setup/main.tf:19]: nit: we can take this opportunity to bump to latest version of project factory and update the setup providers as well.

File: test/integration/simple_example/controls/gcloud.rb [hunk 4]
```diff
@@ -12,12 +12,24 @@
...
+project_id = attribute("project_id")
+region = attribute("region")
+cloud_router_name = attribute("cloud_router_name")
+
 control "gcloud" do
-  title "gcloud"
+  title "Gcloud checks: enabled compute api, and cloud router existence"
 
-  describe command("gcloud --project=#{attribute("project_id")} services list --enabled") do
+  describe command("gcloud --project=#{project_id} services list --enabled") do
```
Comment (bharathkkb) [inline test/integration/simple_example/controls/gcloud.rb:22]: nit: I think this check is not necessary as the module is not responsible for enabling this api.

File: Makefile [hunk 5]
```diff
@@ -18,7 +18,7 @@
 # Make will use bash instead of sh
 SHELL := /usr/bin/env bash
 
-DOCKER_TAG_VERSION_DEVELOPER_TOOLS := 0
+DOCKER_TAG_VERSION_DEVELOPER_TOOLS := 0.13.3
```
Comment (bharathkkb) [inline Makefile:21]: @morgante this uses the `0.13.x` image for tests but imho as everything works fine, I think we can keep it.

Comment (bharathkkb) [inline Makefile:21]: @parabolic nit: we should pin to minor image version `0.13` so this can automatically get patch updates when `0.13.4,0.13.5` etc releases.

**Comment by bharathkkb** [comment]
@parabolic apologies this fell off my radar. I will try to get the triggers set up in https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/778
/cc @umairidris

**Comment by bugg123** [comment]
Any chance of getting these conflicts fixed up and this into a release?

File: test/fixtures/simple_example/main.tf [hunk 6]
```diff
@@ -25,8 +25,36 @@ resource "random_pet" "main" {
 }
 
 module "example" {
-  source = "../../../examples/simple_example"
+  source = "../../../examples/simple"
 
-  project_id  = var.project_id
-  bucket_name = random_pet.main.id
+  project = var.project_id
+  name    = random_pet.main.id
```
Comment (umairidris) [inline test/fixtures/simple_example/main.tf:31]: I see a variable name defined but here it seems to use a random id. Should the var be removed?

File: test/fixtures/simple_example/main.tf [hunk 7]
```diff
@@ -25,8 +25,36 @@ resource "random_pet" "main" {
...
+
+module "vpc" {
+  source  = "terraform-google-modules/network/google"
+  version = "~> 2.5"
+
+  project_id   = var.project_id
+  network_name = random_pet.main.id
+  routing_mode = "GLOBAL"
+
+  subnets = [
```
Comment (umairidris) [inline test/fixtures/simple_example/main.tf:44]: The router being created doesn't seem to use any subnet or secondary range, so I would just remove these fields.

File: examples/simple/variables.tf [hunk 8]
```diff
@@ -0,0 +1,35 @@
...
+}
+
+variable "region" {
+  type        = string
+  description = "The GCP region"
```
Comment (umairidris) [inline examples/simple/variables.tf:34]: Set a default value

File: examples/simple/variables.tf [hunk 9]
```diff
@@ -0,0 +1,35 @@
...
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+variable "name" {
+  type        = string
+  description = "Name of the router"
+}
+
+variable "network" {
```
Comment (umairidris) [inline examples/simple/variables.tf:22]: It seems a network is being created in the test, remove this var?

**Review by umairidris — APPROVED** [review]

**Comment by umairidris** [comment]
Thanks for adding these tests!

File: test/fixtures/simple_example/main.tf (hunk 6 above)
Comment (bharathkkb) [reply test/fixtures/simple_example/main.tf]: It seems like the author was passing the name to the example. Hardcoded this in examples.

File: test/fixtures/simple_example/main.tf (hunk 7 above)
Comment (bharathkkb) [reply test/fixtures/simple_example/main.tf]: done

File: examples/simple/variables.tf (hunk 9 above)
Comment (bharathkkb) [reply examples/simple/variables.tf:17]: @umairidris not sure I follow, we need to pass in the name of the network that is created in the fixture to the simple example right?

File: examples/simple/variables.tf (hunk 8 above)
Comment (bharathkkb) [reply examples/simple/variables.tf]: Hardcoded now as that is preferred for CFT examples over default vars.

File: examples/simple/variables.tf (hunk 9 above)
Comment (umairidris) [reply examples/simple/variables.tf:17]: Ops, I misread!
